n = 10

for i in range(n):
    switchApp("Microsoft Excel")
    sleep(0.1)
    type("c", Key.CMD) 
    sleep(0.1)
    type("c", Key.CMD)
    type(Key.RIGHT)  
    sleep(0.2)
    switchApp("Google Chrome")
    sleep(0.1)
    type("a", Key.CMD)
    type("v", Key.CMD)
    type(Key.TAB)
    sleep(0.2)
    switchApp("Microsoft Excel")
    sleep(0.1)
    type("c", Key.CMD)  
    sleep(0.1)
    type("c", Key.CMD)
    type(Key.DOWN)
    sleep(0.1)
    type(Key.LEFT)
    sleep(0.2)
    switchApp("Google Chrome")
    sleep(0.1)
    type("a", Key.CMD)
    type("v", Key.CMD)
    type(Key.TAB)
    sleep(0.1)
    type(Key.TAB)
    sleep(0.2)